### ISSUE TITLE
i am getting response with empty string.

### ISSUE THREAD

**Issue by shivwork** [roryrjb/iplocation#16]
Code
------
iplocation('14.140.116.138').then((res) => {
      console.log('res :->', res);
    });
---------------------
Console 
--------
res = {
country: '',
...
}

**Comment by roryrjb** [comment]
Hey @shivwork thanks for raising this. I have tested with the latest versions in `6.x`, `5.x` and `4.x` branches and cannot replicate. This can happen if there isn't a value from the IP metadata provider, but for this particular IP address all the data is there. I could also have been a temporary issue with the provider at the time. If this issue persists, please let me know and could you also include the output of `DEBUG=iplocation node {your_script_name}.js` which will include information about what providers the module tried, what responses it got, etc.

**Comment by ntk860** [comment]
I am also getting empty response.

**Comment by ntk860** [comment]
@roryrjb can you help me please ?

**Comment by roryrjb** [comment]
@ntk860 if you are able to share a snippet of the code you are using and ideally the IP address so I can properly test this then that would be good, otherwise if you could tell me what fields are empty.

**Comment by ntk860** [comment]
```
iplocation('56.70.97.8').then((res) => { 
        // res is empty
        console.log(res)
    })
    .catch(error => {
        console.log(error)
    })
})
```

{ country: '',
  countryCode: '',
  region: '',
  regionCode: '',
  city: '',
  postal: '',
  ip: '',
  latitude: null,
  longitude: null,
  timezone: '' }

**Comment by ntk860** [comment]
@roryrjb thank you for trying to help

**Comment by roryrjb** [comment]
@wtfleming thanks for pointing this out. I reached a similar fix when looking at this but wanted to get a more permanent solution in place, it seems like we may not be able to continue relying on _ipapi.co_, so will look for some alternative. @ntk860 if you are able to implement something similar to this fix I think it'll be the best short term solution.

**Comment by jlchereau** [comment]
```
iplocation('90.254.60.95', [], callback);
```

Return an empty record as experienced by https://github.com/roryrjb/iplocation/issues/16#issuecomment-444948053.

```
iplocation(
    '90.254.60.95',
    [
        'https://ipinfo.io/*',
        'https://ipapi.co/*/json/'
    ],
    callback
);
```

Returns a proper record as suggested by https://github.com/roryrjb/iplocation/issues/16#issuecomment-445018349
