### ISSUE TITLE
when using promises, It doesn't report RateLimited as an error

### ISSUE THREAD

**Issue by omidmaldar** [roryrjb/iplocation#17]
Hi, this is the message that promise resolves after facing a RateLimited error. shouldn't be a rejection instead?

{
    "error": true,
    "reason": "RateLimited",
    "message": "Sign up for IP Address Location API @ https://ipapi.co"
}

**Comment by jlchereau** [comment]
This is actually the same as #16 and is fixed by https://github.com/roryrjb/iplocation/pull/19

**Comment by roryrjb** [comment]
Fixed in 7bb576f440de0bfa0585c3cbcded22ac21e2ee6d, many thanks @jlchereau.

This has been released as `6.1.0` in __npm__: https://www.npmjs.com/package/iplocation/v/6.1.0.
