### ISSUE TITLE
npmjs reports different version

### ISSUE THREAD

**Issue by FrozenFalcon** [roryrjb/iplocation#2]
The package.json reports version 3.0.0 but npmjs only serves version 2.0.1. This causes confusion as the docs are different too.

**Comment by roryrjb** [comment]
@FrozenFalcon thanks for bringing this to my attention again. The reason for the difference is that I was having some issues with the GeoIP API that is used in versions `<= 2.x` and I found an alternative provider and bumped the version to `3.0.0`, but both actually still work, _it was a temporary issue with the original provider_; so I never actually pushed `3.0.0` to __NPM__ as it wasn't really necessary. I haven't used either provider that much. If you use this module perhaps you could help me find out which is better if there is a difference at all, or maybe it would be a good idea to have a primary and fallback provider using both. I don't necessary have the time to look at this now, but maybe you could contribute a pull request to somehow resolve the inconsistency.
