### ISSUE TITLE
How to pass API key

### ISSUE THREAD

**Issue by prasoon0304** [roryrjb/iplocation#36]
I want to add API key . Where I can add it ?

**Comment by Richienb** [comment]
That's currently not an option. PR welcome.

**Comment by prasoon0304** [comment]
It works only with free service of API?

**Comment by Richienb** [comment]
Yes. Pr welcome.

https://ipapi.co/#pricing

<blockquote><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAu1JREFUeNq0V99P01AUPrft5oZMSwgkGGPQPRjkZYhR548M1BATY1iU+Js4HsyCJOr+AWV/gNkw+kB8YCY+aTQQ4steNvSFJ9M9+ABGKJohGAIFFWZZe72FASG0o70dJ2l207Oe853vnvudFoFFY4aGa4GVg8D9C5CLBy4HNfISuLAs+H/lh15fDvdbiYdMJ05+4YFZjgEnh7SkJHnhWl3jwrp+Li+2jTqi3bc7EyUDwH4Y82FWTq1WvJFUD4C2LsMyhDLuxIvgg45tC9s2+UDWB5hJkSVvlq1FB4ZEoxTqGoj32QYAGPVZSb4BQoXB+rlQb2/vI2oA7PuZENklH1DaD16GT4fmnxAQPB0DGD0s5q7O5UXyky72n49eSUsetAyAffObN6rerahwf3w6MXUmeFD1tTVjpDaQ25IuCxU5WHDlW2kYMKT+xs9p8fnNO+sdjuvbBUCKYcePVy7W0jehjh2fl7aIDT58z1CA3Musr6QAsrtcWypCIy8Nq1QYLJUUwGB1VZB0dtNmCpiY4ZF0KoKRjzNEfc2TZt/N6voye8oh5t2XOpZ8G/9cDRmifncxyE1GsRq/77UOoFCWpuchPc9ouYs8jYjI5Ioqun98RQJe0W0BUqNg01pGKtLhcFigAqBcqRILLFCZX/RAzYIzam8W2GCh+ZsnQapP2wKgtO4nLFgHcVbcLR2QnBH703CFBRwnfSaaTV65yMK5sbIIqV4qCQDlklciW9FhuvHGXOnuW12mese0EKktR8he4m3f9+pmWCkw4TQN1poSIjViNPXW7MKEI0qoF3cEgHr+qNaQPUb+U1lGeHa1M27pLdvy2dIaUoeFsjzAySkUsRrOMgA14Jf0WKibhfTT68XPfMmmYYGFTRaYVKgECwGlMcPJvrWPFO/fJeHr6fYGqjjUUwapA+vznmN6qAuhfVA9cVHTBMmdx/BY+NNPG4ezN2xxv0NFvBnJ3RkACA8tcAxvJ4RdBgQbfbxi/wUYAOrtCs1T5pPJAAAAAElFTkSuQmCC" width="48" align="right"><div><strong><a href="https://ipapi.co/#pricing">ipapi - IP Address Lookup and Geolocation API | No SignUp</a></strong></div><div>Enterprise IP Location by Kloudend, USA is built on AWS & trusted by Fortune 500. Supports JSON, CSV, XML in PHP, JS, Java, Python, Go, Ruby & C#.</div></blockquote>

**Comment by prasoon0304** [comment]
If I purchase then I want to add key in API . Is it possible to add ?

**Comment by Richienb** [comment]
Not yet. PR welcome.

**Comment by prasoon0304** [comment]
So I need to go with the normal api call and do right?

**Comment by Richienb** [comment]
Right now, API keys are optional. The function currently doesn't have a way to accept them so if you want that functionallity, a pull request is welcome.

**Comment by prasoon0304** [comment]
Yes . Is ther any possibility for local modification?
