### ISSUE TITLE
Basic test failed

### ISSUE THREAD

**Issue by arupadhy** [roryrjb/iplocation#37]
Can someone check if this module is being maintained.
Basic test failed with latest version and works fine with 6.x

```
const ipLocation = require("iplocation");

(async () => {
    await ipLocation("172.217.167.78");
})();
```

With 7.x (latest), i see the following error
HTTPError: Too Many Requests

**Comment by Richienb** [comment]
Version 7 removes a bunch of endpoints to ensure the results are consistent for each run. However, because less services are used, it is much easier to hit the cap hence `HTTPError: Too Many Requests`.
