### ISSUE TITLE
Freegeoip deprecation warning

### ISSUE THREAD

**Issue by MartijnDevNull** [roryrjb/iplocation#8]
Freegeoip will be deprecated on Juli first and needs to be replaced with https://ipstack.com

See: https://github.com/apilayer/freegeoip#readme

**Comment by roryrjb** [comment]
@MartijnDevNull thanks for pointing this out. Does anyone using this module have any suggestions of alternatives providers we could use instead? IP Stack _is_ free but will require an API key which I'd like to avoid providing an option for, as in, this module was designed to just use free services without keys to make it as easy and quick as possible.

**Comment by MartijnDevNull** [comment]
There are more providers that don't require registration/API keys: https://ahmadawais.com/best-api-geolocating-an-ip-address/

**Comment by roryrjb** [comment]
fixed in 31be03aaecb5886b7a1e9912f6a68040cf6886a7
