### ISSUE TITLE
Different JSON structures from providers

### ISSUE THREAD

**Issue by tohagan** [roryrjb/iplocation#9]
Each of the providers produces slightly different JSON structures.  So what I think this lib needs is an optional transform function per provider to convert the JSON into a set of common fields.
Some of the providers DO produce similar results so they could become the defacto standard.

**Comment by roryrjb** [comment]
@tohagan yes very good point. I'm happy to accept a pull request for this, otherwise I can probably work on it this weekend.

**Comment by tohagan** [comment]
Some also now require an access key that you could include as an input.
The result they return can depend on whether you present a key.

**Comment by roryrjb** [comment]
The _different structure_ issue is closed in https://github.com/roryrjb/iplocation/pull/14, with an initial implementation. Regarding the need for API keys, I've trimmed the default provider list so none require API keys, but the actual implementation needs to be addressed, I've opened https://github.com/roryrjb/iplocation/issues/15 for this. As always PRs are more than welcome! :+1:
